### ISSUE TITLE
there is no way to get current widget or paas in user data when set callback

### ISSUE THREAD

**Issue by Q191** [pwiecz/go-fltk#10]
func (w *widget) SetCallback(f func()) {

---------------------------

![image](https://user-images.githubusercontent.com/83848311/159119717-21f6a857-0559-4daa-a912-48d91ab56f5d.png)

**Comment by pwiecz** [comment]
I'm not sure, I see the problem.
You can pass any closure as the parameter to SetCallback. And the closure can capture the widget or user data.

userData := "xxx" 
btb.SetCallback(func(){onButtonPressed(btn, userData)})

Maybe it's not the easiest way, but it seems doable.

**Comment by Q191** [comment]
Yes, I get it. Thanks for your reply.

```
	for i := 0; i < len(config); i++ {
		ii := i
		radionButtons[i].SetCallback(func() {
			fn(ii)
		})
	}
```
