### ISSUE TITLE
Add interface for Fl_Check_Browser

### ISSUE THREAD

**Issue by diegoefe** [pwiecz/go-fltk#108]
Don't forget to add interface to checked(int), checked(int, bool) and int| nchecked () const (rationale in #109)

**Comment by pwiecz** [comment]
@diegoefe I've implemented the CheckBrowser type. Please specify if you need any more methods.

**Comment by diegoefe** [comment]
@pwiecz seems like that the Text(int) is missing

**Comment by pwiecz** [comment]
@diegoefe done. :)

**Comment by diegoefe** [comment]
Thanks! I'll let you know if any other fundamental method is missing

**Comment by diegoefe** [comment]
Hi @pwiecz, I forgot to ask you to implement addWithData() and Data(), sorry!

**Comment by pwiecz** [comment]
@diegoefe As far as I can tell, `Fl_Check_Browser` does not support having data together with an item.
https://www.fltk.org/doc-1.4/classFl__Check__Browser.html

**Comment by diegoefe** [comment]
I guess you're right even though I thought I used this widget with data.
I'm sorry. I guess I'll just have to handle the data externally.
