### ISSUE TITLE
Can this be used on Mac M1 (with arm processor)?

### ISSUE THREAD

**Issue by marcelloh** [pwiecz/go-fltk#112]
"The FLTK libraries are bundled with the repo for x86_64 Linux, MacOS and Windows (mingw64)."
To me this is like: only works on x86_64 platforms, or did I misunderstood?

**Comment by pwiecz** [comment]
Arm64 libs for MacOS are also provided thanks to @MoAlyousef.
The text should be made more clear, I guess.

**Comment by marcelloh** [comment]
Ok, thanks for the clarification.
When I tried, I got an error, but that's probably because idk if I have  a
c++ compiler in my laptop :-)

Op do 12 okt 2023 om 12:53 schreef pwiecz ***@***.***>:
