### ISSUE TITLE
Build failure on windows github actions runner

### ISSUE THREAD

**Issue by MoAlyousef** [pwiecz/go-fltk#115]
I noticed the failing action builds on windows, and it seems to be related to the update of the mingw toolchain to 12.2:

https://github.com/bytecodealliance/wasmtime-go/issues/192
https://github.com/gen2brain/go-fitz/issues/96
https://github.com/actions/runner-images/issues/8266

We can either downgrade the mingw toolchain in the check.yaml  `- run: choco install mingw --version 11.2.0.07112021 --allow-downgrade`, or update the windows-gnu binaries.

**Comment by pwiecz** [comment]
I've added this downgrade command, but I still can see MinGW 12.2 being used: `C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe` .
I'll try uploading new windows libraries soon.

**Comment by pwiecz** [comment]
After updating libraries all the actions seem to pass.
