### ISSUE TITLE
Fl_Grid

### ISSUE THREAD

**Issue by vlappa** [pwiecz/go-fltk#116]
Interesting brand new feature in fltk 1.4.0 Fl_Grid

Maybe a bit early to implement it, but eventually a nice one.

"I'm asking everybody who is interested in new Fl_Grid widget to test and for feedback, particularly if something is unclear or undocumented. I'll try to help and update docs and code. If you find that some docs are missing, please report as well."

"[Fl_Grid](https://www.fltk.org/doc-1.4/classFl__Grid.html) is, as of FLTK 1.4.0, still in experimental state and should be used with caution. The API can still be changed although it is assumed to be almost stable - as stable as possible for a first release"

https://www.fltk.org/doc-1.4/classFl__Grid.html

**Comment by pwiecz** [comment]
@vlappa sorry for the delay. Some basic functionality has been added with an example basically copied from the Fltk documentation about Fl_Grid.

**Comment by pwiecz** [comment]
Closing the issue. If some additional functionality is needed, please file a new issue.
