### ISSUE TITLE
Newest version (20240101) breaks tabs

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#121]
tabs ok: github.com/pwiecz/go-fltk v0.0.0-20230924064308-597b69513d35
not ok:  github.com/pwiecz/go-fltk v0.0.0-20240103212031-a509cedbac17

If you build [minicalc](https://github.com/mark-summerfield/minicalc) it correctly shows tabs & they work fine.  (Might be worth adding minicalc to ShowCase.)

But if you do `go get -u ./...` to update to the newest release of go-fltk the tabs don't appear at all & the UI is all messed up.

**Comment by pwiecz** [comment]
Still looking into it. Not sure what's going on.
One thing I can see, that for me setting `buttonHeight` to value e.g. `40` makes the tabs visible.
Still sizing of the controls is way off...

**Comment by mark-summerfield** [comment]
OK, I've solved the problem, which is that MeasureText() doesn't always return a sensible value (e.g., sometimes you get 0, 0). I'm going to remove all uses of MeasureText from my code.
I've just done and update of minicalc without MeasureText and with the latest go-fltk and now it works fine.
