### ISSUE TITLE
Can't compile on linux arm64

### ISSUE THREAD

**Issue by vlappa** [pwiecz/go-fltk#124]
I'm not able to build my app, based on the texteditor example on Arm64.
```
$ ./build
# github.com/pwiecz/go-fltk
box.cxx:3:10: fatal error: FL/Fl_Box.H: No such file or directory
    3 | #include <FL/Fl_Box.H>
      |          ^~~~~~~~~~~~~
compilation terminated.

Same happens when trying to build the texteditor example itself.

**Comment by pwiecz** [comment]
what does ./build invoke?

**Comment by pwiecz** [comment]
I see, that the file cgo_linux_arm64 is missing... did you get it generated
when you've called go generate last time?

**Comment by vlappa** [comment]
Probably my bad, I only copied the files in /lib

The file is here:
https://github.com/vlappa/go-fltk/blob/arm64_2/cgo_linux_arm64.go

**Comment by pwiecz** [comment]
That's my fault, as you did what I suggested in my comment.
https://github.com/pwiecz/go-fltk/issues/113#issuecomment-1892848760
I'll add the missing files in a minute.

**Comment by vlappa** [comment]
Not sure if that fixes it completely. I used go.work file to select the generated go-fltk source and then I get:

```
$ go build main.go
# github.com/pwiecz/go-fltk
gl_window.cxx:7:10: fatal error: GL/glx.h: No such file or directory
    7 | #include <GL/glx.h>
      |          ^~~~~~~~~~
compilation terminated.

When trying to build the texteditor example

**Comment by pwiecz** [comment]
@vlappa you may need to install libglx-dev package.

**Comment by pwiecz** [comment]
cgo_linux_arm64.go added in  ed128b67b1b541e7780d363c0aa10d51b4d45134

**Comment by vlappa** [comment]
libglx-dev and libgl-dev

Another error:

```
# command-line-arguments
/opt/go/pkg/tool/linux_arm64/link: running g++ failed: exit status 1
g++: error: /home/pi/go-fltk/lib/linux/arm64/libfltk_gl.a: No such file or directory

```
go-fltk/lib/linux/arm64 $ ls
FL  libfltk.a  libfltk_forms.a  libfltk_images.a  libfltk_jpeg.a  libfltk_png.a  libfltk_z.a

**Comment by vlappa** [comment]
Maybe I should run 'go generate' with libglx-dev and libgl-dev installed?

Then I get:

```
go build main.go
# command-line-arguments
/opt/go/pkg/tool/linux_arm64/link: running g++ failed: exit status 1
/usr/bin/ld: cannot find -lGLU
collect2: error: ld returned 1 exit status

**Comment by pwiecz** [comment]
Right... I wasn't paying attention before.
You need to have _gl generated

**Comment by vlappa** [comment]
Here is the new generated repo with _gl: https://github.com/vlappa/go-fltk/tree/arm64_3

Currently stuck on the ld error.

**Comment by vlappa** [comment]
Ok, for the ld error to fix I needed to install: libglu1-mesa-dev (Debian)

Now it compiles. 

So, is this https://github.com/vlappa/go-fltk/tree/arm64_3 repo enough for you, or do you need another pull request?

You did have linux/arm (32 bit) already right? Or do you want me to give that a shot as well?
https://github.com/pwiecz/go-fltk/issues/113#issuecomment-1764603174

**Comment by pwiecz** [comment]
@vlappa  I have linux/arm(32) built on my RaspberryPi, but somehow I've forgotten to add it to the repo.

**Comment by pwiecz** [comment]
Thanks, I've added the _gl libraries and libraries for linux/arm.

**Comment by vlappa** [comment]
Thanks!
