### ISSUE TITLE
Image memory leak

### ISSUE THREAD

**Issue by mgord9518** [pwiecz/go-fltk#15]
There is a small memory leak associated with NewSvgImageFromString(), possibly others but I haven't tested them.

To reproduce, create a loop such as:
```
for {
    image, _ := NewSvgImageromString(...)
    defer image.Destroy()
}
```

And the memory usage will slowly rise. It looks like the image pointer isn't being completely destroyed.

**Comment by pwiecz** [comment]
One issue about your loop is that the `defer` works in the function scope not the block scope.
The rise of the memory usage is expected here.
You can try running  :
```
func createAndDestroy() {
  image, _ := NewSvgImageFromString(...)
  defer image.Destroy();
}
  for {
    createAndDestroy()
  }
```

**Comment by mgord9518** [comment]
You're right, I guess I was debugging incorrectly. Looks like the memory leak is actually from SetBoxType(), but I have zero clue what would cause it. Maybe the function pointers are never getting deleted? It only appears to happen when a variable is set in the draw function

**Comment by pwiecz** [comment]
When triggers the memory leak?
Calling `SetBoxType` with the same `boxType` over and over again?

**Comment by mgord9518** [comment]
Call SetBoxType on a box used by a resizable widget, then resize the window to trigger redrawing. Any variables set inside the draw function aren't GC'd for some reason

**Comment by pwiecz** [comment]
Can you send a small code that reproduces the issue?

**Comment by mgord9518** [comment]
```go
package main

import (
        "fmt"

        "github.com/pwiecz/go-fltk"
)

func draw(x, y, w, h int, c fltk.Color) {
        r, g, b := 100, 100, 100
        svgData := fmt.Sprintf(`<?xml version='1.0'?><svg width='%d' height='%d' xmlns='http://www.w3.org/2000/svg'>
    <rect stroke-width='1' rx='5' width='%d' height='%d' fill='rgb(%d, %d, %d)' stroke='rgb(142, 176, 218)' y='1' x='1'/>
  </svg>`, w, h, w-2, h-2, r, g, b)
        image, _ := fltk.NewSvgImageFromString(svgData)
        defer image.Destroy()
        image.Draw(x, y, w, h)
}

func main() {
        win := fltk.NewWindow(100, 100)
        fltk.SetBoxType(fltk.UP_BOX, draw, 0, 0, 0, 0)

        button := fltk.NewButton(10, 10, 80, 80, ":(")

    win.Resizable(button)
        win.End()
        win.Show()
        fltk.Run()
}
```

Then just monitor its memory usage while resizing

**Comment by pwiecz** [comment]
I've tried on Linux and Windows.
I can see memory usage go up and down, probably as GC is firing.
But I did not notice any steady increase in memory usage... :(

**Comment by mgord9518** [comment]
Bizzare, I mean I think it's a good thing that it isn't reproducible, makes me wonder if there's some issue with my system. Maximizing that window would cause it to take up over 20MB, then continue slowly rising until the resizing stops, but never goes back down

**Comment by pwiecz** [comment]
I could make the memory usage go up slightly over 20MB when running on Linux.
But I couldn't make it grow more after that.

**Comment by mgord9518** [comment]
Guess it must be some caching thing and not a leak which is relieving. Unrelated, but how do you do event handling (eg click and drag)? I see the events defined in the code but have no clue on how to implement it

**Comment by pwiecz** [comment]
You can specify a callback for a widget using `SetCallback` and later inside it call `fltk.EventType()` etc.
Some widgets can have event handlers specified directly e.g. `GlWindow' or `TableRow`

**Comment by mgord9518** [comment]
Is it possible to do it with plain boxes or is that not yet implemented? Boxes don't seem to respond to events like buttons do. In the C++ example I'm going off of it basically creates a box then links it with a drag event

**Comment by pwiecz** [comment]
Can you post a link to the C++ example?
The only way I found to make the event handling really work was to create a subclass of a particular widget and override the `handle()` method.
Look at gl_window.cxx or table.cxx - they both support event handling in pretty identical way.
Maybe using some magic c++ tricks you can limit the code duplication ;) , but I'm not sure it's worth it.

**Comment by pwiecz** [comment]
I've added SetEventHandler method to the Box widget.
You can run:
package main
```
import (
	"fmt"

	"github.com/pwiecz/go-fltk"
)

func onBoxEvent(event fltk.Event) bool {
	if event == fltk.PUSH {
		fmt.Println("PUSH")
		// return true to receive drag events
		return true
	} else if event == fltk.DRAG {
		fmt.Println("DRAG")
		return true
	}
	return false
}
func main() {
	win := fltk.NewWindow(100, 100)
	box := fltk.NewBox(fltk.UP_BOX, 10, 10, 80, 80)
	box.SetEventHandler(onBoxEvent)
	win.End()
	win.Show()
	fltk.Run()
}

```

**Comment by mgord9518** [comment]
And here's the C++ example
```C++
//
// "$Id$"
//
//     A simple demo of drag+drop with FLTK. 
//     Originally from erco's cheat sheet, permission by author.
//     Inspired by Michael Sephton's original example posted on fltk.general.
//
//     When you run the program, just drag the red square over
//     to the green square to show a 'drag and drop' sequence.
//
// Copyright 1998-2010 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     http://www.fltk.org/COPYING.php
//
// Please report all bugs and problems on the following page:
//
//     http://www.fltk.org/str.php
//

#include <stdio.h>
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>

// SIMPLE SENDER CLASS
class Sender : public Fl_Box {
public:
  // Ctor
  Sender(int x,int y,int w,int h) : Fl_Box(x,y,w,h) {
    box(FL_FLAT_BOX);
    color(9);
    label("Drag\nfrom\nhere..");
  }
  // Sender event handler
  int handle(int event) {
    int ret = Fl_Box::handle(event);
    switch ( event ) {
      case FL_PUSH: {             // do 'copy/dnd' when someone clicks on box
        const char *msg = "It works!";
        Fl::copy(msg,strlen(msg),0);
        Fl::dnd();
        ret = 1;
        break;
      }
    }
    return(ret);
  }
};
// SIMPLE RECEIVER CLASS
class Receiver : public Fl_Box {
public:
  // Ctor
  Receiver(int x,int y,int w,int h) : Fl_Box(x,y,w,h) {
    box(FL_FLAT_BOX); color(10); label("..to\nhere");
  }
  // Receiver event handler
  int handle(int event) {
    int ret = Fl_Box::handle(event);
    switch ( event ) {
      case FL_DND_ENTER:          // return(1) for these events to 'accept' dnd
      case FL_DND_DRAG:
      case FL_DND_RELEASE:
        ret = 1;
        break;
      case FL_PASTE:              // handle actual drop (paste) operation
        label(Fl::event_text());
        fprintf(stderr, "Pasted '%s'\n", Fl::event_text());
        ret = 1;
        break;
    }
    return(ret);
  }
};
int main(int argc, char **argv) {
  // Create sender window and widget
  Fl_Window win_a(0,0,200,100,"Sender");
  Sender a(0,0,100,100);
  win_a.end();
  win_a.show();
  // Create receiver window and widget
  Fl_Window win_b(400,0,200,100,"Receiver");
  Receiver b(100,0,100,100);
  win_b.end();
  win_b.show();
  return(Fl::run());
}

//
// End of "$Id$".
//
```

**Comment by pwiecz** [comment]
Hi
I've added a translation of the code above into Go as an example: [https://github.com/pwiecz/go-fltk/blob/main/examples/dnd/main.go](https://github.com/pwiecz/go-fltk/blob/main/examples/dnd/main.go)
It required implementing a couple of helper functions.
