### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by MoAlyousef** [pwiecz/go-fltk#3]
Hi
I would like to add image support if that’s ok (would require linking fltk_images, fltk_jpeg, fltk_png and fltk_z on all systems).  
Regarding the api, since some images can be constructed from data and/or files, I’m thinking of something like:
```go
image, err := fltk.SvgImageLoad("image.svg")

image, err := fltk.SvgImageString("<svg></svg>") // or SvgImageData
```

**Comment by pwiecz** [comment]
Linking any "official" fltk library seems ok to me.

I wonder if the second function name wouldn't sound better as `fltk.SvgImageFromString` as it more clearly shows that it's a constructor function. Or even `NewSvgImageFromString` ...
