### ISSUE TITLE
Browser::HideLine

### ISSUE THREAD

**Issue by MoAlyousef** [pwiecz/go-fltk#30]
Hi @mgord9518 
I noticed that the code for Browser::HideLine is commented out with:
https://github.com/pwiecz/go-fltk/blob/9378e0027427cceb11d025261692c553b3c287e8/browser.go#L52

FLTK browsers have 1 based indexing, and uncommenting that code (and relevant C++ code) works correctly, it might crash with input (line == 0 or line >= browser.size()), but these checks can be added to the Go side of things.

**Comment by mgord9518** [comment]
@MoAlyousef Thank you! I missed this because somehow I managed to call HideLine before actually populating the browser in my test. I'll add it in my next PR
