### ISSUE TITLE
Can I set a window icon?

### ISSUE THREAD

**Issue by kernelPanic0x** [pwiecz/go-fltk#38]
Hello.

How can I set a window Icon?

Is the window.SetImage() function the right way? Because that does nothing for me.

**Comment by pwiecz** [comment]
window.SetImage() is only setting image part of widget's label: https://www.fltk.org/doc-1.4/classFl__Widget.html#aff29d81e64b617158472f38d2cac186e
Setting window icon in Fltk seems pretty cumbersome. :(
In fact I've personally never got around to doing it for my apps... and many Fltk apps are not using any window icons as far as I can tell.
In (the original c++) Fltk source code you can see, how it's done for sudoku app https://github.com/fltk/fltk/blob/master/test/Makefile#L594  for Golang you'd probably have to embed icon in application using e.g. https://github.com/tc-hib/go-winres and do something else for OSX and I'm not sure what to do under Linux. :(

**Comment by MoAlyousef** [comment]
Fltk has a `Fl_Window::icon(Fl_Image *)` method which sets the window’s icon in the toolbar (upper left corner). Setting the app’s icon however requires other tools like windres etc.

**Comment by pwiecz** [comment]
Right, I've interpreted question as a question about the app icon not the window icon. 
Adding method `Window.Icon()` seems doable.

**Comment by kernelPanic0x** [comment]
Yes I mean the app Icon in the upper left corner. I am settings the file Icon already with rsrc. That would be a great addition :)
