### ISSUE TITLE
example in README uses OFLAT_FRAME which doesn't exist

### ISSUE THREAD

**Issue by jessehorne** [pwiecz/go-fltk#41]
The example in the README currently uses `btn.SetBox(fltk.OFLAT_FRAME)`. I had to change this to `btn.SetBox(fltk.OVAL_FRAME)` to get it to work.

**Comment by MoAlyousef** [comment]
Yeah this should be OFLAT_BOX. The actual example was updated but the README wasn’t. 
I’ll send a PR with the update when I get home.
