### ISSUE TITLE
svg icons

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#47]
I prefer to use SVG images for my icons & for the app icon.
But Window.SetIcons only accepts ftlk.RgbImages. FLTK supports the use of SVG images so would it be possible to add Window.SetIcon(fltk.SvgImage) ?

**Comment by MoAlyousef** [comment]
I've opened a [pull request](https://github.com/pwiecz/go-fltk/pull/49) for this. FLTK normally supports only raster images for icons, hence the signature with RgbImage. Svg is a special case in that it's not a raster type, but FLTK actually normalizes it automatically if used for an icon. With the linked PR, this should be possible:

```go
package main

import (
	"github.com/pwiecz/go-fltk"
)

func main() {
	win := fltk.NewWindow(300, 200)
	svg := `<svg viewBox='0 0 100 100'>
	<circle cx='50' cy='50' r='50' fill='red'/>
	</svg>`
	svgimg, err := fltk.NewSvgImageFromString(svg)
	if err != nil {
		panic(err)
	}
	rgbIconSvg := fltk.NewRgbImageFromSvg(svgimg)
	win.SetIcons([]*fltk.RgbImage{rgbIconSvg})
	win.End()
	win.Show()
	fltk.Run()
}
```

**Comment by mark-summerfield** [comment]
Works like a charm --- thank you!
