### ISSUE TITLE
Regarding the licensing of go-fltk

### ISSUE THREAD

**Issue by MoAlyousef** [pwiecz/go-fltk#5]
Hello
Would you consider changing the license to a more permissive license?
The FLTK license for example is basically lgpl with an exception allowing static linking.

**Comment by pwiecz** [comment]
Sure. As it's "only" bindings to another library, any LGPL2-compatible license works for me.

I could copy the FLTK license, but I does contain the hand-written FLTK-specific clause which I would like to avoid.

I could go as permissive as: https://spdx.org/licenses/MIT.html 

Any preferences? There's your code there as well.

**Comment by MoAlyousef** [comment]
I personally like MIT since it’s easy to understand and easy to copy even into another application.
