### ISSUE TITLE
[question] what is the go-fltk equivalent to fltk-rs's Flex layout widget?

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#52]
In fltk-rs there's a Flex widget which supports laying out widgets horizontally or vertically. What's the go-fltk widget that does this?

**Comment by MoAlyousef** [comment]
FLTK adopted osen/FL_Flex recently, so the code is there, just needs wrapping in Golang

**Comment by mark-summerfield** [comment]
Flex widget has been added - thank you.
