### ISSUE TITLE
[question] How to limit Tabs label height

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#53]
I have some code like this:
```go
const BUTTON_HEIGHT = 32
window = fltk.NewWindow(512, 480)
window.Resizable(app.window)
window.SetLabel(APPNAME)
width := app.window.W()
height := app.window.H()
tabs := fltk.NewTabs(0, 0, width, height)
tabs.SetAlign(fltk.ALIGN_TOP)
// tabs.SetLabelHeight(BUTTON_HEIGHT) // has no effect
height -= BUTTON_HEIGHT // Allow room for tab
group := fltk.NewGroup(x, y, width, height, "A&bout")
view := fltk.NewHelpView(x, y, width, height)
view.SetValue(aboutHtml())
group.End()
// etc
```
It runs fine & correctly shows the tabs. But when I increase the size of the window by dragging or maximizing, although _most_ of the extra space goes to the tab groups, _some_ goes to the tabs themselves making them far taller than needed. Is it possible to set their maximum height to BUTTON_HEIGHT?

**Comment by MoAlyousef** [comment]
You could try adding `tabs.Resizable(view)`, this should limit the resizing to not be symmetric all over.

**Comment by pwiecz** [comment]
You can read it https://www.fltk.org/doc-1.4/classFl__Tabs.html under the section "Resizing Caveats".

**Comment by mark-summerfield** [comment]
Thank you both, using `tabs.Resizable(view)` as Mo said & as the docs pwiecz mentioned indicate worked.
