### ISSUE TITLE
[request] Complete support for Choice and MenuButton

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#60]
At the moment it is not possible to dynamially populate a Choice or MenuButton.
Yet this is often a requirement. For example, in https://github.com/mark-summerfield/minicalc I am using an Input for calculator expressions, but I'd prefer to use a Choice which shows the last expression, and the expression before that, and so on for the previous, say 7 expressions. But the current Choice API doesn't support this.
Similarly at the moment I have two Copy buttons to copy specific things, but I'd prefer a Copy MenuButton whose items I could change dynamically.

**Comment by pwiecz** [comment]
Hi @mark-summerfield I've added some basic methods for modifying menu items.
Please tell if you need something more.

**Comment by mark-summerfield** [comment]
Although using a MenuButton now works fine, using a dynamically populated Choice doesn't work.
For example, if the user enters some text "my name", using choice.Value() returns the _index_ of the entry, but there is no method exposed in Go to return the current entry's string value. The C++ API has text() methods that do this.

The use case I have is:
- Initially the choice is empty.
- Whenever the user presses Enter I want to
  1. Add the text to the choice so that it can be selected rather than typed in future (and if there are too many items in the choice, delete the oldest ones)
  2. Call a callback with the text to process the text

**Comment by mark-summerfield** [comment]
Thanks for adding those. However, I've only just realised that the widget I need is https://www.fltk.org/doc-1.4/classFl__Input__Choice.html 
The Choice alone is fine if you have predefined strings, but I want each expression the user enters to be added to the choice so they can go back and choose earlier ones to select & edit.

**Comment by pwiecz** [comment]
@mark-summerfield I've just added the `InputChoice` widget. Hope it helps. :)
