### ISSUE TITLE
[request] HelpView scroll to End

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#61]
I have a HelpView in minicalc which gets repopulated after every calculation in the Evaluator tab. Once the size of the html page is too long the HelpView correctly adds a vertical scrollbar. But I cannot find a way to scroll the HelpView so that the last line is visible. I've tried  SetTopLine and SetTopLineString but neither help. I just need a ScrollToEnd() method.

**Comment by pwiecz** [comment]
I don't want to add a special helper functions that are not in the base Fltk itself.
What works for me, I think, is:
```
fmt.Println("Scrolling to bottom")
helpView.SetTopLine(1000000)
helpView.SetTopLine(helpView.TopLine() - helpView.H())
```

Calling `SetTopLine()` with a humongous parameter makes the `HelpView` scroll down, making the last line being just above the visible area.
Then by scrolling up by the widget height one can make the last line move to the bottom of the widget.
It's not a most elegant solution, but it somehow works.
If you want to expand the Fltk API, please ask the Fltk developers...

**Comment by mark-summerfield** [comment]
Thank you, that worked perfectly.
