### ISSUE TITLE
[request] support redrawing after resizing

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#62]
When I resize minicalc with the Evaluator tab showing, the layout does not automatically re-layout. I tried to solve this:
```go
	app.Window.SetResizeHandler(func() { // app.Window is of type *fltk.Window
		fmt.Println("resize")
		app.Window.Redraw()
	})
```
This prints 'resize' on the console, but does _not_ force the layout to re-layout.

**Comment by MoAlyousef** [comment]
I've noticed the `// TODO Doesn't work: need Flex`, the Flex widget was added some days ago. Sorry I didn't update the issue. Can you try and see if it addresses the problem?

**Comment by mark-summerfield** [comment]
I've replaced my Packs with Flexes and now I have correct live resizing behavior just as I wanted. Thank you!
