### ISSUE TITLE
[possible bug] When EventType() is Key letters are only matched if CTRL is down

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#65]
Here's a simplified version:
```go
window := fltk.NewWindow(640, 480)
window.SetEventHandler(func(event fltk.Event) bool {
	switch fltk.EventType() {
	case fltk.KEY:
		switch fltk.EventKey() {
		case fltk.ESCAPE:
			return true
		case fltk.HELP, fltk.F1:
			fmt.Println("help")
			return true
		case fltk.F2:
			fmt.Println("F2")
			return true
		case 'q', 'Q': // only triggered with CTRL! -- is this correct or a bug???
			fmt.Println("Q")
		}
	case fltk.CLOSE:
		window.Destroy()
	}
	return false
})
```
To try it out run https://github.com/mark-summerfield/minicalc (>= v1.1.1) and press 'Q' or 'q' in one of the Inputs and then try Ctrl+q (which should quit)

**Comment by pwiecz** [comment]
Hi on which @mark-summerfield what operating system are you seeing this behaviour?
I've just tried this under Linux and it prints Q whenever I press q.

**Comment by mark-summerfield** [comment]
I don't think this is a bug after all.
If the user presses plain q or Q in an Input the Input correctly handles it; otherwise it gets passed up and the window handler ends up with it.
