### ISSUE TITLE
[poss. bug] callback stops being called

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#66]
I have attached a go-fltk app that has a bug. The bug occurs in _my_ code, but I _believe_ it is due to a bug in go-fltk. I think this because the same thing happened before with a previous go-fltk app I created.

At first I thought the problem was due to me keeping the whole app's state in a pointer to a single struct, e.g.,
```go
type App struct {
	*fltk.Window
	config         *Config
	tabs           *fltk.Tabs
	evalView       *fltk.HelpView
	evalInput      *fltk.InputChoice
	evalResults    []EvalResult
	evalCopyButton *fltk.MenuButton
	regexView      *fltk.HelpView
	regexInput     *fltk.InputChoice
	regexTextInput *fltk.InputChoice
	asciiView      *fltk.HelpView
	customView     *fltk.HelpView
}
```
and passing this pointer to a callback, and that some kind of locking occurs under the hood so that after a while the callback stops being called. But this isn't the case.

Anyway, to reproduce the bug: build or go run the attached `callback_bug.zip`. When it starts up you should be on the Evaluator tab. Press and *hold* the _Enter_ key. This will output a number in the HelpView. After 30-40 repeats **holding down _Enter_  will stop having any effect: this is the bug**. If you close the app (click X close button or press Ctrl+Q) and rerun and repeat holding Enter, the number it gets up to varies from run to run, i.e., is _not deterministic_ which is why I think it is go-fltk rather than me.

The bug occurs on the file `evaluator_tab.go` in the `onEval` callback defined in the function `makeBottomRow`.
If you comment out lines 43 (`userVarNames := ...` ) and 59 (`nextVarName = onEval(...`), and rerun, the bug will _not_ occur: the numbers will continue to be output.

So, on the face of it the problem is in _my_ code (i.e., in `onEval` or one of its callees); however, I don't believe that my code is the real problem: I think it is a go-fltk issue.

[callback_bug.zip](https://github.com/pwiecz/go-fltk/files/11071019/callback_bug.zip)

Last time I had this problem, the solution I found was instead of passing a pointer to the whole App struct, I passed in pointers to just those widgets etc. that I needed to access.  So I tried this solution with minicalc, but it didn't work. Here's the code with this approach:

[callback_bug2.zip](https://github.com/pwiecz/go-fltk/files/11071051/callback_bug2.zip)

So right now I don't know how to fix this.

**Comment by pwiecz** [comment]
Hi @mark-summerfield 
There was a bug in the version of the binding you were using. :(
Updating to the newest version should fix the problem.
I've called `go get github.com/pwiecz/go-fltk@latest` rebuild and restarted the program. And I couldn't reproduce the bug.
Best!

**Comment by mark-summerfield** [comment]
Hi @pwiecz  I've retried and the bug is gone! Thank you :-D
