### ISSUE TITLE
[question] static building for windows on linux

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#67]
I can cross-compile a windows .exe on linux using this .sh script:
```sh
go-winres simply --icon images/icon.ico
CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc \
    CXX=x86_64-w64-mingw32-g++ \
    go build -buildvcs=false -ldflags -H=windowsgui -o minicalc.exe .
```
But unfortunately, this uses _dynamic_ linking which means the target windows machine _must_ have mingw's dlls installed and in the `PATH`.

Is it possible to create a completely standalone .exe (i.e., statically linked) for windows from linux? And if so, how?

**Comment by MoAlyousef** [comment]
I'm not sure if replacing this line
https://github.com/pwiecz/go-fltk/blob/bbcb6d0a16204fc518fed8bb8247a49a8f617102/fltk.go#LL6-L6C29

with:
```
#cgo amd64,windows LDFLAGS: -static -L${SRCDIR}/lib/windows/x64 -lfltk -lfltk_images -lfltk_z -lfltk_png -lfltk_jpeg -lfltk_gl -lglu32 -lopengl32 -lgdiplus -lgdi32 -luser32 -lole32 -lcomctl32 -luuid -lws2_32 -lcomdlg32 -static-libgcc -static-libstdc++
```
might help.

Maybe also using zig as a windows cross-compiler might help as well, since I think it statically links its C++ std lib by default.

However I can't test either solution at the moment.

**Comment by mark-summerfield** [comment]
Solved:
```
go-winres simply --icon images/icon.ico
CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc \
    CXX=x86_64-w64-mingw32-g++ \
    go build -buildvcs=false \
	-ldflags="-H=windowsgui -extldflags=-static" \
	-o minicalc.exe .
```
Creates a 12MB binary but works!

**Comment by MoAlyousef** [comment]
I think `strip minicalc.exe` would still work on a mingw built executable.
