### ISSUE TITLE
Global tooltip control

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#75]
In fltk-rs it is possible to globally switch tooltips on or off: https://docs.rs/fltk/latest/fltk/misc/struct.Tooltip.html#method.enable
I think this would be useful for go-fltk.
(If you add it I will add a checkbox to the ui-config example to show its use.)

**Comment by pwiecz** [comment]
Thanks for the suggestion. :)
I've added `EnableTooltips`, `DisableTooltips`, `TooltipDelay` and `SetTooltipDelay` functions.

**Comment by mark-summerfield** [comment]
Thanks! I have added these functions to the `ui-config` example: see https://github.com/pwiecz/go-fltk/pull/77
