### ISSUE TITLE
ChoiceDialog improvements

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#83]
The ChoiceDialog has a title bar with no title and does not show the application icon.
It would be nice if both could be set.

**Comment by MoAlyousef** [comment]
Hi Mark,

Regarding the dialog taking the app's icon, I'm not sure FLTK supports this. You would probably need to spawn a modal window to serve as a dialog.

@pwiecz 
fl_message_title would also work for fl_choice. 
I have a fix but that would probably break the current behavior of ChoiceDialog, it would require a title string to be passed:
```go
func ChoiceDialog(title string, message string, options ...string) int
```

**Comment by mark-summerfield** [comment]
I'll create my own modeless window and a wrapper function to do this instead.
Thanks.
