### ISSUE TITLE
callbacks can't return error

### ISSUE THREAD

**Issue by vlappa** [pwiecz/go-fltk#87]
Handling errors is important in Go, but callbacks are expected to be of type func() in go-fltk. Shouldn't that become: func() error?

https://github.com/pwiecz/go-fltk/blob/main/menu.go#L48

**Comment by pwiecz** [comment]
Can you, please, elaborate, how would you use this error value in menu callback?

**Comment by mark-summerfield** [comment]
You don't need to return an error: and in fact in a callback you can't since the callback is called by the system not by you.

The solution for handling errors in callbacks is to use a closure, e.g.,

```go
widget.SetCallback(func() { 
if err := doSomething(); err != nil {
    app.handleError(err) // app is some type that's been captured by the closure
}
```
})

**Comment by vlappa** [comment]
I see, thx. Callbacks are a bit magical to me still. I'm starting to see how closures can be useful.

**Comment by vlappa** [comment]
Made a small app based on the texteditor example
https://github.com/vlappa/session-notes
