### ISSUE TITLE
How to use a gorotine to update widgets? AwakeNullMessage seems not working.

### ISSUE THREAD

**Issue by jcbritobr** [pwiecz/go-fltk#9]
Hi. Very nice work.

I would like to know how I can update a progess bar or other widgets using a goroutine. I'm trying something like the code below, but AwakeNullMessage seems not working.
```go
package main

import (
	"fmt"
	"time"

	"github.com/pwiecz/go-fltk"
)

func main() {

	win := fltk.NewWindow(400, 200)
	win.SetLabel("Go Fltk")
	progress := fltk.NewProgress(10, 10, 250, 40, "Progress")
	progress.SetMaximum(99)
	progress.SetMinimum(0)
	button := fltk.NewButton(10, 50, 80, 30, "Clique-me")
	button.SetColor(fltk.GREEN)
	button.SetCallback(func() {
		fmt.Println("Button clicked")
		go func() {
			for i := 0; i < 100; i++ {
				fltk.Lock()
				progress.SetValue(float64(i))
				fltk.Unlock()
				fltk.AwakeNullMessage()// not updating gui
				time.Sleep(300 * time.Millisecond)
			}
		}()
	})
	win.Resizable(button)
	win.End()
	win.Show()
	fltk.Run()
}
```

There are a way to acquire something like that?

**Comment by MoAlyousef** [comment]
Hello
FLTK requires enabling the global lock first. This can be done by calling fltk.Lock() before calling fltk.Run():
```go
fltk.Lock()
fltk.Run()
```

**Comment by pwiecz** [comment]
Right.
`fltk.Lock()` should most likely be called even before `win.Show()`

**Comment by jcbritobr** [comment]
Hello, that worked. Thank you. I'll build a set o examples based on erko's page to contribute with this repo. It will be good to test the code also.

**Comment by jcbritobr** [comment]
Im observing that I need no unlock to update the widgets. Is It ok only use AwakeNullMessage after the change?

**Comment by MoAlyousef** [comment]
I think it's ok to remove the Lock/Unlock around progress.SetValue(), as long as the data is local to that goroutine

**Comment by pwiecz** [comment]
@jcbritobr what system did you test it on?
I wouldn't be surprised if it differed between Linux and Windows.

**Comment by jcbritobr** [comment]
> @jcbritobr what system did you test it on? I wouldn't be surprised if it differed between Linux and Windows.

Testing on windows 11 with msys2 and mingw64-gcc 11xx

**Comment by jcbritobr** [comment]
If there is no problem, I would like to record here the problems I encounter while writing the examples of the erkos page. Is it ok?

**Comment by pwiecz** [comment]
Sure, report the problems you see.

By the way, I'm still not convinced that you can safely skips locking or unlocking. There may be a potential race condition lurking there.

**Comment by MoAlyousef** [comment]
You’re right. According to the [multithreading docs](https://www.fltk.org/doc-1.3/advanced.html), fltk calls from different threads need to call lock then unlock so the drawing won’t be interfered from any other thread (including the ui thread).

**Comment by jcbritobr** [comment]
Let me ask another thing about widgets. There is the fl_draw(..) function implemented?

**Comment by MoAlyousef** [comment]
Some are implemented, they can be found in drawings.go.
