### ISSUE TITLE
Missing screen functions

### ISSUE THREAD

**Issue by vlappa** [pwiecz/go-fltk#90]
https://www.fltk.org/doc-1.4/group__fl__screen.html

Functions like [Fl::h](https://www.fltk.org/doc-1.4/group__fl__screen.html#ga7f42d75cf9b3e79bbe39e1041a657cdf) (), are missing if I'm not mistaken. 

I was looking for Fl::w()

https://github.com/pwiecz/go-fltk/blob/bb29d08ae9a231d7cfb9fc77e95ea21738089c83/fltk.go#L250

**Comment by pwiecz** [comment]
I'm wondering whether I should add all the screen sizing functions, or maybe some are not that useful.
@vlappa maybe it would be enough to use `ScreenWorkArea` for some particular screen.
My problem with `Fl::w` is that the documentation does not specifies that it "Returns the width in pixels of the main screen work area.", but does not specify what the "main screen" really is... :/

**Comment by vlappa** [comment]
ScreenWorkArea does the job fine for me atm.
