### ISSUE TITLE
Example app: gviz

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#94]
The [Gviz](https://github.com/mark-summerfield/gviz) app I'm finishing up now is essentially complete. It is < 2KLOC yet shows:
- standard menu bar with dynamically updated recent files list
- two toolbars both hideable/showable
- a modeless dialog (help dialog)
- modal dialogs including ones that provide results (e.g., ask_form, find_form), and a "smart" live updates dialog (config_form)
- use of a Tile and a Scroll
- several event handlers

So it might be worth linking to as an example to supplement the docs. Anyway, that's up to you. (Either way, please just close this issue once you've read it. I'd have emailed but don't know your address & there's no discussion link I can see.)

**Comment by pwiecz** [comment]
Thanks! I'll add it soon. Sorry for the slow responding. I'm swamped with other work right now. :(

**Comment by mark-summerfield** [comment]
I've added another example, a simple Linux ogg audio player: [PlayTrack](https://github.com/mark-summerfield/playtrack).

**Comment by pwiecz** [comment]
Added a Showcase section at the bottom of the README.md.
