### ISSUE TITLE
Subtle crash with dynamic menu

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#95]
I have a reproducable crash in [Gviz](https://github.com/mark-summerfield/gviz) which I can't figure out.

1. Preparation: run gviz and open one of the eg/*.gv files; repeat this a few times so you have some recent files.
2. Run gviz and press Alt+F,R to pop up the recent files submenu
3. Press Esc
4. Press Alt+O to pop up the file open menu: _all works fine._
5. Run gviz and press Alt+F,R to pop up the recent files submenu
6. Press up arrow to highlight the open menu, then press Enter to select the open menu: **crash.**

The error I get is:
```
Unrecoverable error: runtime error: slice bounds out of range [:-1]
```
But I believe that I don't use `[:-1]` in my code.

**Comment by pwiecz** [comment]
@mark-summerfield 
I've reproduced the crashed and it seems like a bug on the gviz side.
I've disabled `recovery()` calls from gviz.go and gviz under Delve.
The erroneous slice access is in line `onEditorEnter` function: https://github.com/mark-summerfield/gviz/blob/main/editor.go#L106 `raw[:j-1]` when `j` is `0`.
There is similar access couple lines below in `onEditorBackspace`

**Comment by mark-summerfield** [comment]
@pwiecz  you are right it was my mistake.
My bug affected 3 methods: `onEditorEnter`, `onEditorBackspace`, and `onEditorDelete`. In each case if the insertion position is `<= 0` then the work is passed back to fltk to do the default action. My bug was to check for `< 0`.

I did try delve without success. But your mentioning disabling recover has showed me why it didn't work for me, so at least I'll be able to try it in future.

Thanks!
