### ISSUE TITLE
Context switch caption is always "FLTK"

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#97]
As you can see from the screenshot when I task switch in Linux (Debian XFCE) it correctly shows "MiniCalc" as the application name but under the icon it wrongly shows "FLTK". With other applications the name shown is the same for both, i.e., the application's name.
![screenshot](https://github.com/pwiecz/go-fltk/assets/1773348/7e7d0d8b-0ea6-43a8-bfeb-1908e6c97a26)

**Comment by MoAlyousef** [comment]
I think this would be fixed by setting the xclass of the window, relevant PR: #96

**Comment by pwiecz** [comment]
If the solution doesn't work for you please reopen the issue.

**Comment by mark-summerfield** [comment]
I don't know how to reopen, but it doesn't work (tried with 3 go-fltk apps).

**Comment by MoAlyousef** [comment]
Hi Mark
If you're calling SetXclass after the window is shown, can you try calling it before?
I'm running Kubuntu and it seems to show the window titles in the task switcher, xfce appears to show the xclass, which is by default FLTK:
https://github.com/fltk/fltk/blob/04bf5c5a3405d601f7eb7ffc337a53e3dbb107ae/src/Fl_Window.cxx#L193C17-L193C17

**Comment by mark-summerfield** [comment]
Very sorry, you're quite right, once I called SetXClass it works correctly.
